#!/bin/bash
source environment
ssh -i id_rsa ${USER_NAME}@${IP_ADDR} /bin/bash << EOF

if ps ax | grep -v grep | grep "/bin/bash /home/${USER_NAME}/kegeratorjs/iked sudo /usr/bin/python3 /home/${USER_NAME}/kegeratorjs/src/ikePyIo/ikePyIo.py" > /dev/null
then
    echo "iked is already running"
else
	echo "launched iked"
	nohup /home/${USER_NAME}/kegeratorjs/iked sudo /usr/bin/python3 /home/${USER_NAME}/kegeratorjs/src/ikePyIo/ikePyIo.py > /dev/null 2>&1&
fi
EOF
