#!/bin/bash
source environment
ssh ${USER_NAME}@${IP_ADDR} /bin/bash << EOF
if ps ax | grep -v grep | grep "/bin/bash /home/pi/kegeratorjs/iked sudo /usr/bin/python3 /home/pi/kegeratorjs/src/ikePyIo/ikePyIo.py" > /dev/null
then
  echo "iked is running, killing it"
  sudo kill `ps -ef | grep -v grep | grep "/bin/bash /home/pi/kegeratorjs/iked sudo /usr/bin/python3 /home/pi/kegeratorjs/src/ikePyIo/ikePyIo.py" | awk '{ print $2 }'`
else
  echo "iked is not running"
fi
EOF
