#!/bin/bash
source environment
export PYTHONPATH=${PYTHONPATH}:/Users/nwiles/Documents/kegeratorjs/src/server/
./test/server/ike/api_test.py && \
./test/server/ike/keg_test.py && \
./test/server/ike/lager_UT.py && \
./test/server/ike/thermostat_UT.py
